### ISSUE TITLE
我的路由没有联网但是你的工具判断是wifi，这个怎么解决

### ISSUE THREAD

**Issue by freelf** [iOSSinger/SGNetObserver#1]

**Comment by youngyunxing** [comment]
是第一次吗

**Comment by freelf** [comment]
不管第几次都不可以，我是手机连上wifi，然后改wifi的ip，输入一个错的ip，他是不能上网的，但是用你的库判断是可以连接网络的

**Comment by youngyunxing** [comment]
我这边测试,拔掉路由器网线,或者路由器账号错误都可以识别到,你说的修改wifi的ip,是什么意思,还请详细说明,或者截个图

**Comment by freelf** [comment]
就是我在wifi链接的详细里面，把服务器的ip随便改一个，那么就是没办法上网的，但是用这个库识别还是可以连网的，就是下图那个服务器的地址
![img_1044](https://cloud.githubusercontent.com/assets/15242207/20044180/881cd5ea-a4d1-11e6-9a9c-73b3036b2cf2.PNG)
